### ISSUE TITLE
USER STORY: Anonymous voting

### ISSUE THREAD

**Issue by otherworldly94b** [otherworldly94b/My-first-Agile-project#4]
In order to **allow users to vote anonymously** as a **running community website**, I can **create an option for the voting to be anonymous for those who do not want to share this kind of data**

**Acceptance Criteria:**

1. The option should be provided as a checkbox
2. The checkbox should be “checked” by default
3. The option should appear next to the submit button
4. After submitting the default submission confirmation should be adjusted to include the user name.

**Tasks**

- [ ] Update the admin module view: the poll design (HTML and CSS) to include a date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate that the expiry date is at least after 3 days.
- [ ] Create a job to check the expired Polls every day at 11:59PM and Hide them
- [ ] Update the controller function
- [ ] Update the unit test scripts
- [ ] Test the functionality

**Comment by otherworldly94b** [comment]
Acceptance Criteria:

1. The option should be provided as a checkbox
2. The checkbox should be “checked” by default
3. The option should appear next to the submit button
4. After submitting the default submission confirmation should be adjusted to include the user name.
